version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stderr
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - goheader
    - gomodguard
    - ireturn
    - lll
    - maintidx
    - mnd
    - modernize
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - nolintlint
    - perfsprint
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    gosec:
      excludes:
        - G115
    lll:
      line-length: 132
    staticcheck:
      checks:
        - all
        - -ST1000
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_ssz\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_ssz\.go$
      - third_party$
      - builtin$
      - examples$
